### ISSUE TITLE
Twitter / Telegram Bot 

### ISSUE THREAD

**Issue by Corentinrhr** [farukekim/honeypotdetector#3]
Hey,
I would like to develop a Twitter / Telegram bot that automatically scans the token contracts we send it. Is it possible to collaborate with you to have the source code of your project for this purpose?

**Comment by Thedexplorer** [comment]
satılamayan tokenlere dair bir check atıyor musun yoksa sadece fee mi?

**Comment by farukekim** [comment]
We are not going to share source codes with anyone. It's not an open source project. We are working on api, you can use api soon.
