### ISSUE TITLE
Broken Contract Module 

### ISSUE THREAD

**Issue by dexvdev** [farukekim/honeypotdetector#4]
satılamayan tokenlere dair bir check atıyor musun yoksa sadece fee mi?

**Comment by farukekim** [comment]
Uygulama satılamayan coinler için honeypot uyarısı veriyor. Örnek olarak https://detecthoneypot.com/scan?chain=avax&address=0x351116480614d80fc00ada7cdbc40e72e6636cdf

**Comment by selimekim94** [comment]
Contract yayinlanir yayinlanmaz kontrol edebiliyor. Ayrica yeni guncelleme ile henuz liquidity eklenmemis contractlari da kontrol edebileceksiniz.
