### ISSUE TITLE
API ?

### ISSUE THREAD

**Issue by bL34ch-exe** [farukekim/honeypotdetector#5]
Hello do u know when the API will be released ?

**Comment by selimekim94** [comment]
![msg1649278833-17877](https://user-images.githubusercontent.com/37869309/160618361-5175bdbd-efb6-473c-b63a-600a02724eb7.jpg)
Sorry for late reply. Api will be released asap. Right now working on cronos chain.

**Comment by Gillardo** [comment]
Love to use API, please let me know when available

**Comment by Gillardo** [comment]
any news on this?

**Comment by selimekim94** [comment]
> any news on this?

https://rapidapi.com/selimekim94/api/honeypotapi/
If you prefer crypto for payment, let me know. Also you can test the free package
